In [1]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('student_data.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df.groupby("性別")[['國文', '英文', '數學', '地理', '歷史']].agg('mean')

       國文     英文     數學     地理     歷史
性別
女   76.84  67.48  70.12  65.60  73.76
男   66.28  73.16  66.60  72.96  68.44

In [2]:
scores_df

     國文  英文  數學  地理  歷史   姓名 性別
1    75  62  54  77  75  林小明  男
2    81  55  95  57  79  陳曉華  女
3    80  53  51  70  74  張大偉  男
4    92  97  92  55  88  李靜宜  女
5    67  91  43  52  64  王志豪  男
6    82  77  72  78  82  黃美玲  女
7    50  92  86  90  59  趙國強  男
8    75  60  61  74  92  孫雅婷  女
9    85  81  41  76  88  周正雄  男
10   62  78  97  87  99  吳淑芬  女
11   55  91  70  52  86  鄭志強  男
12   44  50  69  99  51  劉惠君  女
13   51  50  62  65  64  郭銘宏  男
14   84  57  57  69  54  陳建豪  男
15   51  89  52  41  89  楊玉珍  女
16   49  53  99  45  59  賴志明  男
17   97  80  71  50  82  朱雅惠  女
18   75  65  40  54  46  徐佳玲  女
19   99  87  59  50  57  林俊傑  男
20   97  42  63  92  63  曾小梅  女
21   95  61  49  98  97  葉宏達  男
22   54  45  84  78  57  蘇佩君  女
23   45  77  82  84  78  潘文凱  男
24   87  60  53  53  55  盧曉潔  女
25   93  83  58  54  71  梁家豪  男
26   63  93  97  55  43  許美華  女
27   64  98  53  95  68  鍾政廷  男
28   78  50  91  41  55  沈宜蓁  女
29   70  45  66  64  70  簡大維  男
30   76  71  70  44  95  蔡淑惠  女
31   46  66  80  79  50  彭志遠  男
32   92  77  94  65  97  郭盈君  女
33   57  40  93  90  69  詹家銘  男
34   60  50  55  47  93  顏欣怡  女
35   84  77  92  88  48  傅國華  男
36   93  46  75  69  45  方雅婷  女
37   62  81  77  90  62  謝志強  男
38   96  96  74  63  86  侯惠敏  女
39   54  54  61  78  98  鄧志誠  男
40   73  79  54  74  96  白美玲  女
41   41  80  87  49  64  洪大山  男
42   87  90  43  77  87  康雅慧  女
43   98  83  98  80  52  施志偉  男
44   46  40  56  93  92  邱淑芬  女
45   45  84  60  99  73  游建興  男
46   87  43  80  99  55  廖美君  女
47   47  97  42  49  72  高文傑  男
48  100  76  55  45  42  溫雅琪  女
49   61  86  45  81  59  古志剛  男
50   73  78  60  50  75  柳惠珍  女

In [3]:
scores_df['總分'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)

scores_df['總分階級'] = pd.cut(
    scores_df['總分'],
    bins=[0, 250, 350, 500],
    labels=['低分區', '一般區', '高分區']
)

scores_df.groupby(['性別', '總分階級'])['總分'].agg(['count', 'mean', 'min', 'max'])

C:\Users\user\AppData\Local\Temp\ipykernel_25436\3054408475.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  scores_df.groupby(['性別', '總分階級'])['總分'].agg(['count', 'mean', 'min', 'max'])

         count        mean    min    max
性別 總分階級
女  低分區       0         NaN    NaN    NaN
   一般區      11  315.454545  280.0  336.0
   高分區      14  383.928571  351.0  425.0
男  低分區       0         NaN    NaN    NaN
   一般區      13  322.769231  292.0  349.0
   高分區      12  374.166667  352.0  411.0